services:
  mysql-db:
    image: mysql:8.0.43
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: tsmstlu_db
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:
      - mysql_data_v2:/var/lib/mysql
    networks:
      - backend
    # Thêm đoạn này để kiểm tra sức khỏe Database
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  tsms-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tsms-app
    ports:
      - "8080:8080"
    environment:
      # SỬA DÒNG NÀY: Thêm allowPublicKeyRetrieval=true và useSSL=false
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-db:3306/tsmstlu_db?allowPublicKeyRetrieval=true&useSSL=false"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: "123456"
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      mysql-db:
        condition: service_healthy # Chỉ chạy khi MySQL đã HEALTHY
      redis:
        condition: service_started
    networks:
      - backend

volumes:
  mysql_data_v2:

networks:
  backend:
    driver: bridge